### ISSUE TITLE
Improve usability and standard of functionality

### ISSUE THREAD

**Issue by alberttheprince** [Qbox-project/qbx_radio#12]
-

**Comment by ChatDisabled** [comment]
1. Already available in the config
2. Personal preference per server owner
3. Personal preference per server owner
4. Personal preference per server owner

**Comment by alberttheprince** [comment]
-

**Comment by alberttheprince** [comment]
-

**Comment by ChatDisabled** [comment]
If we add all the functionality there is to add, the poor paid content creators won't be getting any bread anymore. And I have never played on a server with a player list of the radio channel. As this would be straight powergaming. You also don't get a list of connected devices when using radio's in real life? This would prevent RP where one would sneakily connect with a gang's preferred frequency.

**Comment by alberttheprince** [comment]
-
